### ISSUE TITLE
Small images don't look good with blog image styles

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/littleweaverweb.com#20]
<img width="1188" alt="messages image 2916601644" src="https://cloud.githubusercontent.com/assets/1051450/12400538/b0d5aedc-bdee-11e5-9c4e-dff88a4dd6fb.png">

**Comment by nmorduch** [comment]
I'm not sure if we need to have separate types of image blocks for small and large images, or if we need to detect the image size

**Comment by harrislapiroff** [comment]
I wish wagtail provided options on blocks. Something less than a separate block type but more than one-size-fits-all.

**Comment by nmorduch** [comment]
See http://wagtail.littleweaverweb.com/blog/cameron-higby-naquin-little-weaver/

**Comment by nmorduch** [comment]
An easy way to deal with this is to make a text block and put the image in that. The text blocks are what are width-constrained.

**Comment by nmorduch** [comment]
I'm going to close this for now.

**Comment by melinath** [comment]
Putting the image into a text block isn't really a fix... Using an image block is a semantic issue, not just a stylistic one. (IMO)
