### ISSUE TITLE
Animated gifs don't work on the blog (or probably anywhere tbh)

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/littleweaverweb.com#21]
This is sad :(

![](http://i.giphy.com/AYKv7lXcZSJig.gif)

**Comment by nmorduch** [comment]
See http://wagtail.littleweaverweb.com/blog/cameron-higby-naquin-little-weaver/

**Comment by nmorduch** [comment]
This looks like an easy fix http://docs.wagtail.io/en/v1.3.1/topics/images/advanced_topics.html?highlight=gif#animated-gif-support

**Comment by melinath** [comment]
This is resolved by b217a35
