### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by chigby** [littleweaver/littleweaverweb.com#23]
Right now, the "Get in Touch" link on the home page goes to a contact page that doesn't exist. Something should probably be there.

A lot of businesses have some kind of contact form, but we don't necessarily have to.

**Comment by nmorduch** [comment]
We can make an easy email form if we want. I don't find them super exciting, tbh

**Comment by nmorduch** [comment]
So we have a page but it doesn't work and it not in the nav. @harrislapiroff do we want to use it? 

http://wagtail.littleweaverweb.com/contact/

**Comment by melinath** [comment]
@nmorduch What doesn't work about it exactly?

**Comment by nmorduch** [comment]
I think I was getting an error when I tried to go to the page before. Closing.
