### ISSUE TITLE
Set banner images in admin for all pages

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/littleweaverweb.com#24]
Including:

- [x] Blog index
- [x] Blog posts

If there is none set for a page, there should be a default.
If there is none set for a blog post, it should get the one for the blog index.

What that says to me is that every page should have the option to have one, and should default to that of its parent? but i'm not sure if that's super feasible.

**Comment by melinath** [comment]
The model side of this is done, but most of the logic here will be taken care of on the template side.

**Comment by nmorduch** [comment]
Thanks @melinath i'll let you know if i have questions :)

**Comment by harrislapiroff** [comment]
Done.
