### ISSUE TITLE
Make Contact Us a button

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/littleweaverweb.com#36]
Or at least call it out a little better (in the footer)

**Comment by emilyhorsman** [comment]
<img width="1022" alt="screen shot 2016-02-21 at 9 18 07 pm" src="https://cloud.githubusercontent.com/assets/3536823/13207788/a3577012-d8e0-11e5-8349-c6c44ff27110.png">

Thoughts?

**Comment by emilyhorsman** [comment]
Better yet, with a FA icon on to the left of the button label

**Comment by harrislapiroff** [comment]
Generally into the outline button idea. Uncertain about the fa icon.

Also interested in having a button in the navbar like Caktus's "Get Started" but that'll be a little trickier to fit on our current smaller viewport navbars.

![screen shot 2016-02-23 at 10 13 47](https://cloud.githubusercontent.com/assets/296631/13255861/2da152c0-da16-11e5-81b0-414c0b82d4bb.png)

**Comment by nmorduch** [comment]
@emilyhorsman I like your design :+1:
