### ISSUE TITLE
Vertically centered headers so content is flush with each other in Our Services

### ISSUE THREAD

**Issue by emilyhorsman** [littleweaver/littleweaverweb.com#37]
Like this:
<img width="647" alt="screen shot 2016-02-21 at 9 32 40 pm" src="https://cloud.githubusercontent.com/assets/3536823/13208015/c62ea04a-d8e2-11e5-946d-fad819dc19ca.png">

Instead of this:
<img width="643" alt="screen shot 2016-02-21 at 9 33 52 pm" src="https://cloud.githubusercontent.com/assets/3536823/13208021/d640e560-d8e2-11e5-9210-f4269e27b0d2.png">

Thoughts?

**Comment by harrislapiroff** [comment]
:+1:
