### ISSUE TITLE
Use Wagtail CMS site settings for page meta

### ISSUE THREAD

**Issue by emilyhorsman** [littleweaver/littleweaverweb.com#41]
http://docs.wagtail.io/en/v1.2/reference/contrib/settings.html

OpenGraph and meta values are currently hard coded into the template. They should be extracted into Wagtail settings.

We appear to be decided on an expanded meta description, as follows.

>Little Weaver Web Collective is a cooperative web development agency. We create websites and applications that are beautiful, accessible, and robust. Our team values diversity and keeps strong principles in mind for all work.

**Comment by melinath** [comment]
From slack: Maybe “social responsibility” instead of "strong principles"?

**Comment by emilyhorsman** [comment]
Working on this now, text as it will stand:

>Little Weaver Web Collective is a cooperative web development agency. We create websites and applications that are beautiful, accessible, and robust. Our team values diversity and keeps social responsibility in mind for all work.
