### ISSUE TITLE
Improve reading experience re column placement on narrow screens

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/littleweaverweb.com#46]
It's weird reading blog posts or case studies where on sm screens you have this big margin on the left and none on the right. I'd like to rejigger our cols to feel better there.

**Comment by harrislapiroff** [comment]
For the record, I don't think this is that weird. I'd like a bit more margin on the right, but uneven spacing around text columns due to sidebars at the top of a page or what have you is pretty standard around the web. (see: daringfireball.net, airbagindustries.com, nyt.com)

**Comment by harrislapiroff** [comment]
Or rather I think the solution should be small rather than big. I agree the margin on the right is too tight.

**Comment by nmorduch** [comment]
Literally none of your examples are responsive tho

**Comment by harrislapiroff** [comment]
nyt.com is

**Comment by nmorduch** [comment]
It has a mobile version w/ different design

**Comment by nmorduch** [comment]
jk my browser is being weird

**Comment by harrislapiroff** [comment]
Our layout also doesn't have this problem at "mobile" sizes, though, just as NYT doesn't. At "tablet" sizes our layout displays with an offset column, just as NYT's does.

**Comment by nmorduch** [comment]
For some reason my browser is not currently showing me responsiveness, so I'll respond when I can actually look at those (ugh)

**Comment by nmorduch** [comment]
Double jk, I forgot that github isn't responsive

**Comment by nmorduch** [comment]
I do think that more margin on the right would help. I also think we *might* want to decrease margin on the left if our column gets too narrow

**Comment by harrislapiroff** [comment]
Fair.

**Comment by nmorduch** [comment]
I was never saying like move the column to the left or anything. Just that the current experience feels icky to me, regardless of how other people are doing it,

**Comment by harrislapiroff** [comment]
My argument about how other people are doing it is just to say that people are used to layouts like it and no one is going to ding us too hard for doing the same thing NYT does, y'know? I don't want to overcorrect and work too hard to center the column because I think asymmetrical columns are more interesting and they let us give our logo an interesting role in the layout of the website. I agree that current margins could be adjusted. :)

**Comment by nmorduch** [comment]
Yeah, that's fair :) Our also still feels icky as it currently sits :p

**Comment by nmorduch** [comment]
I should do an audit of column situations in general, I think

**Comment by harrislapiroff** [comment]
Is this roughly resolved?

**Comment by nmorduch** [comment]
Sure
