### ISSUE TITLE
Use Chaparral

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/littleweaverweb.com#5]
We like Chaparral as a font. It will require us getting a Typekit Personal account for $24/yr. Do we like it that much?

**Comment by harrislapiroff** [comment]
I am now -1 on this. Museo seems to suit us well and the fact that it's a family has been useful.

**Comment by harrislapiroff** [comment]
Ah, the difference a year makes.

**Comment by melinath** [comment]
So... closing, I guess?
