### ISSUE TITLE
Better deployment command

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/littleweaverweb.com#62]
Currently the most efficient way to deploy is `fab -H littleweaverweb bootstrap_project:wagtail salt_call`. The obvious way to deploy is `fab -H littleweaverweb full_deploy:production,wagtail` but that reinstalls salt unnecessarily. There should be a shorter `deploy` command, modeled after the way it is done in http://github.com/littleweaver/django-brambling.

**Comment by nmorduch** [comment]
Is this something we can consider done?

**Comment by melinath** [comment]
YES!
