### ISSUE TITLE
Contact Page giving Internal Server Error

### ISSUE THREAD

**Issue by CharleyFarley** [littleweaver/littleweaverweb.com#70]
I am getting this message:

Internal server error

Sorry, there seems to be an error. Please try again soon.

Thought you would like to know!

**Comment by harrislapiroff** [comment]
Thanks for the report! We'll get right on this!

**Comment by melinath** [comment]
I got sendgrid set up but only switched over Dancerfly. :-/ Fixed with 0d79777940ac4e673995153e5dd9756e9052e7ed & preceding commit.
