### ISSUE TITLE
Separate Jobs Page

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/littleweaverweb.com#76]
As opposed to just being a part of the blog.

**Comment by chigby** [comment]
I support this change. I'm not even sure it needs any back-end work? It could be a "Simple Page".

**Comment by melinath** [comment]
It couldn't be a simple page, but it could be a separate blog.

**Comment by melinath** [comment]
So the reasoning here (as I understand it, though I can't find a record of how I got this understanding) is that we want to be able to post jobs and not have them clutter up our blog feed. Additionally we would then be able to "expire" jobs once they're filled, whereas we would not want to remove blog posts basically ever.

**Comment by nmorduch** [comment]
Yes those. Separate blog. Some intro text about general stuff too.

**Comment by nmorduch** [comment]
tbh this isn't really a codebase issue, since i think we can just do a blog page, at least to start. i think the big things are:

-[ ] Writing copy for the page
-[ ] Unpublishing the blog posts

**Comment by nmorduch** [comment]
This is waiting for #28

**Comment by nmorduch** [comment]
I made a simple page to use until the blog design is updated. Should be added to nav either way.

**Comment by nmorduch** [comment]
@cheryllium If you want to add the jobs page to the nav, it just needs to go in the header templates here: https://github.com/littleweaver/littleweaverweb.com/tree/master/core/templates/core/layouts

**Comment by nmorduch** [comment]
Ok I was wrong, this is more complicated. I can do this one.
